// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbuiwjxmodfsimucdqki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhidWl3anhtb2Rmc2ltdWNkcWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDAwNDQsImV4cCI6MjA2MDM3NjA0NH0.04k4JfO3TF57I-9JuU76Bn-cvJwKBLtFsIxU3EQUYM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);